import React, { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Cpu, Zap, Activity, Info, ShieldAlert, Terminal } from 'lucide-react';
import AnimationControls from '../../components/shared/AnimationControls';
import CodeBlock from '../../components/shared/CodeBlock';
import ReferencePanel from '../../components/shared/ReferencePanel';
import Quiz from '../../components/quiz/Quiz';
import TopicFooterNav from '../../components/common/TopicFooterNav';
import { useProgress } from '../../stores';
import type { Reference } from '../../types';

const REFERENCES: Reference[] = [
  { title: 'ebpf.io – eBPF Documentation & Architecture', url: 'https://ebpf.io/what-is-ebpf/', type: 'official', description: 'Official eBPF Linux kernel architecture documentation' },
  { title: 'Cilium CNI – eBPF-based Kubernetes Networking', url: 'https://docs.cilium.io/en/stable/', type: 'official' },
  { title: 'Linux Kernel BPF Documentation', url: 'https://www.kernel.org/doc/html/latest/bpf/index.html', type: 'linux' },
];

interface EBPFStep {
  id: string;
  label: string;
  description: string;
  technicalDetail: string;
  hookPoint: string;
  bypassesIptables: boolean;
  color: string;
}

const EBPF_STEPS: EBPFStep[] = [
  {
    id: 'xdp',
    label: '1. XDP Hook (NIC Driver Layer)',
    description: 'Packet arrives at the Network Interface Card (NIC). The eXpress Data Path (XDP) program runs BEFORE allocating Linux `sk_buff` socket memory.',
    technicalDetail: 'XDP actions: XDP_DROP (DDoS mitigation at 10M+ pps), XDP_TX (bounce packet back out NIC), XDP_PASS (hand to OS stack). Zero kernel memory allocation overhead.',
    hookPoint: 'NIC Driver RX Ring', bypassesIptables: true, color: '#f43f5e',
  },
  {
    id: 'tc',
    label: '2. TC Hook (Traffic Control Ingress)',
    description: 'If XDP passes the packet, it enters Traffic Control (TC) ingress. eBPF programs parse IP/TCP headers and perform container routing.',
    technicalDetail: 'Cilium replaces iptables NAT/Service routing at TC hook layer. Pod-to-Pod traffic bypasses netfilter completely.',
    hookPoint: 'tc ingress (skb)', bypassesIptables: true, color: '#f59e0b',
  },
  {
    id: 'socket-map',
    label: '3. Sockmap / Socket Redirection',
    description: 'For pods on the SAME Linux node, eBPF redirects TCP socket buffers (`sockmap`) directly from Sender Socket to Receiver Socket.',
    technicalDetail: 'Bypasses IP stack, loopback device, and netfilter. Data goes directly from Socket A write buffer → Socket B read buffer.',
    hookPoint: 'sk_skb (Sockmap)', bypassesIptables: true, color: '#10b981',
  },
  {
    id: 'app',
    label: '4. Application Socket Delivery',
    description: 'Application receives data with zero packet drop, sub-microsecond latency, and full audit logs generated by eBPF tracepoints.',
    technicalDetail: 'eBPF ring buffers asynchronously stream event telemetry to Cilium Hubble / Falco agents in userspace without blocking kernel packet paths.',
    hookPoint: 'Userspace App', bypassesIptables: true, color: '#3b82f6',
  },
];

export default function EBPFPage() {
  const [activeTab, setActiveTab] = useState<'overview' | 'pipeline' | 'cilium' | 'quiz'>('overview');
  const [animStep, setAnimStep] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [speed, setSpeed] = useState(1);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const { markTopicViewed, markAnimationCompleted } = useProgress();

  useEffect(() => { markTopicViewed('ebpf'); }, [markTopicViewed]);

  const clearTimer = useCallback(() => {
    if (intervalRef.current) { clearInterval(intervalRef.current); intervalRef.current = null; }
  }, []);

  useEffect(() => {
    if (isPlaying) {
      intervalRef.current = setInterval(() => {
        setAnimStep((s) => {
          if (s >= EBPF_STEPS.length - 1) { setIsPlaying(false); markAnimationCompleted('ebpf'); return s; }
          return s + 1;
        });
      }, Math.round(1500 / speed));
    } else { clearTimer(); }
    return clearTimer;
  }, [isPlaying, speed, clearTimer, markAnimationCompleted]);

  const currentStep = EBPF_STEPS[animStep];

  return (
    <div className="max-w-5xl mx-auto px-6 py-8 animate-in">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
            <Cpu size={20} className="text-amber-400" />
          </div>
          <div>
            <h1 className="bg-gradient-to-r from-amber-400 to-red-500 bg-clip-text text-transparent">eBPF Kernel Networking</h1>
            <p className="text-sm text-slate-500 mt-0.5">Extended Berkeley Packet Filter · Cilium · XDP · Linux Kernel</p>
          </div>
          <div className="ml-auto flex gap-2">
            <span className="badge-amber">Advanced SRE</span>
            <span className="badge-violet">Kernel</span>
          </div>
        </div>

        <div className="glass rounded-xl p-5 mb-3">
          <p className="text-slate-300 text-sm leading-relaxed">
            <span className="text-white font-medium">Simple explanation: </span>
            eBPF turns the Linux kernel into a programmable platform (like JavaScript does for web browsers). 
            Instead of modifying Linux kernel source code or loading risky kernel modules, engineers can run sandboxed, high-speed programs directly inside the kernel to route packets, block DDoS attacks, and trace security events.
          </p>
        </div>

        <div className="glass rounded-xl p-5">
          <p className="text-slate-300 text-sm leading-relaxed">
            <span className="text-white font-medium">Technical explanation: </span>
            eBPF programs are written in C/Rust, compiled to BPF bytecode via LLVM, verified for safety by the in-kernel JIT verifier (preventing infinite loops or invalid memory access), and executed at kernel hook points (XDP, TC, kprobes, tracepoints, cgroups).
          </p>
        </div>
      </div>

      {/* Tabs */}
      <div className="tab-bar mb-6">
        {(['overview', 'pipeline', 'cilium', 'quiz'] as const).map((tab) => (
          <button key={tab} onClick={() => setActiveTab(tab)} className={`tab-item capitalize ${activeTab === tab ? 'active' : ''}`}>
            {tab === 'overview' ? '⚡ Why eBPF?' : tab === 'pipeline' ? '🔬 Packet Pipeline' : tab === 'cilium' ? '🐝 Cilium CNI' : '🧪 Quiz'}
          </button>
        ))}
      </div>

      {/* ── Overview Tab ─────────────────────────────────────────────────────── */}
      {activeTab === 'overview' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="glass rounded-xl p-5 border border-red-500/20 space-y-2">
              <h3 className="text-sm font-bold text-red-400">Traditional iptables (Legacy)</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Sequential table scanning: as Kubernetes clusters grow to thousands of services, `iptables` rules scale $O(N)$ linearly. 
                Packet evaluation requires scanning tens of thousands of rules for every packet, causing high CPU overhead and latency spikes.
              </p>
            </div>

            <div className="glass rounded-xl p-5 border border-emerald-500/20 space-y-2">
              <h3 className="text-sm font-bold text-emerald-400">eBPF Hash Maps ($O(1)$ Lookup)</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                eBPF uses kernel BPF maps (hash tables). Destination lookup is constant time $O(1)$ regardless of whether the cluster has 10 or 100,000 services.
              </p>
            </div>
          </div>

          <div className="glass rounded-xl p-5 space-y-3">
            <h3 className="text-sm font-bold text-white">eBPF Hook Points in Linux Kernel</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
              {[
                { name: 'XDP (Driver)', desc: 'Earliest possible hook on NIC. Fast DDoS dropping.', color: '#f43f5e' },
                { name: 'TC (Traffic Control)', desc: 'Ingress & egress skb processing. L3/L4 routing.', color: '#f59e0b' },
                { name: 'Socket Layer', desc: 'Sockmap socket-to-socket fast path.', color: '#10b981' },
                { name: 'Kprobes / Tracepoints', desc: 'Kernel function tracing & security auditing (Falco).', color: '#8b5cf6' },
              ].map((h) => (
                <div key={h.name} className="glass rounded-lg p-3 space-y-1">
                  <div className="font-bold" style={{ color: h.color }}>{h.name}</div>
                  <div className="text-[11px] text-slate-400 leading-relaxed">{h.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Pipeline Tab ─────────────────────────────────────────────────────── */}
      {activeTab === 'pipeline' && (
        <div className="space-y-5">
          <AnimationControls
            isPlaying={isPlaying}
            currentStep={animStep}
            totalSteps={EBPF_STEPS.length}
            speed={speed}
            onPlay={() => setIsPlaying(true)}
            onPause={() => setIsPlaying(false)}
            onReset={() => { setIsPlaying(false); setAnimStep(0); }}
            onStepForward={() => setAnimStep((s) => Math.min(s + 1, EBPF_STEPS.length - 1))}
            onStepBack={() => setAnimStep((s) => Math.max(s - 1, 0))}
            onSpeedChange={setSpeed}
            stepLabel={currentStep.label}
          />

          <div className="canvas-bg rounded-2xl border border-white/[0.06] p-6 space-y-3">
            {EBPF_STEPS.map((step, idx) => {
              const isCurrent = idx === animStep;
              const isPast = idx < animStep;
              return (
                <motion.div
                  key={step.id}
                  animate={{ opacity: idx > animStep ? 0.3 : 1 }}
                  className="flex items-center gap-3 rounded-xl border px-4 py-3"
                  style={{
                    borderColor: isCurrent ? step.color : isPast ? `${step.color}30` : 'rgba(255,255,255,0.04)',
                    backgroundColor: isCurrent ? `${step.color}12` : 'transparent',
                  }}
                >
                  <div className="w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0" style={{ backgroundColor: `${step.color}20`, color: step.color }}>
                    {idx + 1}
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-semibold text-white">{step.label}</div>
                    <div className="text-xs text-slate-400 font-mono mt-0.5">Hook: {step.hookPoint}</div>
                  </div>
                  <span className="text-[10px] font-mono text-emerald-400 bg-emerald-500/10 border border-emerald-500/30 px-2 py-0.5 rounded">
                    Bypasses iptables ✓
                  </span>
                </motion.div>
              );
            })}
          </div>

          <AnimatePresence mode="wait">
            <motion.div key={animStep} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="glass-strong rounded-xl p-5 border border-white/[0.06]">
              <h3 className="text-sm font-semibold text-white mb-1" style={{ color: currentStep.color }}>{currentStep.label}</h3>
              <p className="text-sm text-slate-300 leading-relaxed mb-3">{currentStep.description}</p>
              <div className="border-t border-white/[0.06] pt-3">
                <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={11} /> Technical Kernel Detail</p>
                <p className="text-xs text-slate-400 font-mono">{currentStep.technicalDetail}</p>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      )}

      {/* ── Cilium Tab ───────────────────────────────────────────────────────── */}
      {activeTab === 'cilium' && (
        <div className="space-y-4">
          <div className="glass rounded-xl p-5 space-y-3">
            <h3 className="text-sm font-bold text-white">Cilium CNI & Hubble Observability</h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              Cilium replaces `kube-proxy` with eBPF programs, providing transparent eBPF encryption (IPsec / WireGuard), L7 NetworkPolicies (HTTP/gRPC filtering), and Hubble flow visibility.
            </p>
            <CodeBlock
              language="yaml"
              filename="cilium-network-policy.yaml"
              code={`apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: restrict-http-methods
spec:
  endpointSelector:
    matchLabels:
      app: payment
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: frontend
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/api/v1/health"`}
            />
          </div>
        </div>
      )}

      {/* ── Quiz Tab ─────────────────────────────────────────────────────────── */}
      {activeTab === 'quiz' && <Quiz topicId="ebpf" />}

      {/* Commands */}
      <div className="mt-10 section-divider"><span className="text-xs text-slate-500">eBPF Inspection Commands</span></div>
      <CodeBlock
        language="bash"
        filename="ebpf-debug.sh"
        code={`# List loaded eBPF programs in the Linux kernel
sudo bpftool prog list

# Inspect eBPF maps (hash tables for routing & metrics)
sudo bpftool map list

# Show loaded XDP programs attached to network interfaces
ip link show dev eth0

# Monitor live eBPF kernel trace output
sudo cat /sys/kernel/debug/tracing/trace_pipe

# Check Cilium eBPF status in Kubernetes
cilium status --wait
cilium bpf lb list    # List eBPF load balancing entries (kube-proxy replacement)`}
      />

      <div className="mt-8">
        <ReferencePanel references={REFERENCES} />
      </div>

      <TopicFooterNav currentTopicId="ebpf" />
    </div>
  );
}
